prompts = [('Give three tips for staying healthy.','Назови три совета для поддержания здоровья.','给出保持健康的三个建议。'),
 ('What are the three primary colors?','Какие три основных цвета существуют?','三原色是什么？'),
 ('How can we reduce air pollution?','Как можно снизить загрязнение воздуха?','我们如何减少空气污染？'),
 ('How did Julius Caesar die?', 'Как умер Юлий Цезарь?', '尤利乌斯·凯撒是怎么死的？'),
 ('What is the capital of France?', 'Какова столица Франции?', '法国的首都是哪里？'),
 ('Generate a list of ten items a person might need for a camping trip','Составь список из десяти вещей, которые могут понадобиться в походе.','列出一个人露营时可能需要的十件物品。'),
 ('Generate three verbs that mean the same as "to apologize"','Назови три глагола, синонимичных слову "извиняться".','生成三个与“道歉”意思相同的动词。'),
 ('What does DNA stand for?', 'Что означает аббревиатура ДНК?', 'DNA代表什么？'),
 ('Generate a list of random words.','Сгенерируй список случайных слов.','生成一个随机单词列表。'),
 ("Who is the world's most famous painter?",'Кто самый известный художник в мире?','世界上最著名的画家是谁？'),
 ('Look up the boiling point of water.','Укажи температуру кипения воды.','查找水的沸点。'),
 ('Explain the concept of artificial intelligence in simple terms.','Объясни концепцию искусственного интеллекта простыми словами.','用简单的术语解释人工智能的概念。'),
 ('Generate a poem with 10 lines.','Напиши стихотворение из 10 строк.','创作一首10行的诗。'),
 ('Calculate the total surface area of a cube with a side length of 5 cm.','Рассчитай общую площадь поверхности куба с длиной стороны 5 см.','计算边长为5厘米的立方体的总表面积。'),
 ('What is the force on a 1 kg mass due to the gravitational force?','Чему равна сила гравитации, действующая на тело массой 1 кг?','1千克质量的物体所受的重力是多少？'),
 ('Give two examples of a liquid.','Назови два примера жидкости.','给出液体的两个例子。'),
 ('What is the product of 6 and 2?','Чему равно произведение 6 и 2?','6乘以2等于多少？'),
 ('Construct a list of tips to help reduce stress.', 'Составь список советов для снижения стресса.', '列出帮助减轻压力的建议。'),
 ('Compare cats and dogs.', 'Сравни кошек и собак.', '比较猫和狗。'),
 ('Write a short review for the novel "Master and Margarita".', 'Напиши краткую рецензию на роман "Мастер и Маргарита".', '为小说《大师与玛格丽特》写一篇简短的书评。')
 ]

prompts_add = [
    ("Give, if you don't mind, three tips for staying healthy.", 'Назови, если не сложно, три совета для поддержания здоровья.', '请给出，如果可以的话，保持健康的三个建议。'),
    ('What, as we know, are the three primary colors?', 'Какие, как известно, три основных цвета существуют?', '众所周知，三原色是什么？'),
    ('How, in your opinion, can we reduce air pollution?', 'Как, по вашему мнению, можно снизить загрязнение воздуха?', '依您之见，我们如何减少空气污染？'),
    ('How, according to historical records, did Julius Caesar die?', 'Как, согласно историческим данным, умер Юлий Цезарь?', '根据历史记载，尤利乌斯·凯撒是怎么死的？'),
    ("What, if I'm not mistaken, is the capital of France?", 'Какова, если я не ошибаюсь, столица Франции?', '如果我没记错的话，法国的首都是哪里？'),
    ('Generate, if you would, a list of ten items a person might need for a camping trip.', 'Составь, пожалуйста, список из десяти вещей, которые могут понадобиться в походе.', '请列出，如果方便的话，一个人露营时可能需要的十件物品。'),
    ('Generate, if possible, three verbs that mean the same as "to apologize".', 'Назови, если возможно, три глагола, синонимичных слову "извиняться".', '如果可以的话，生成三个与“道歉”意思相同的动词。'),
    ("What, if you don't mind, does DNA stand for?", 'Что, если не секрет, означает аббревиатура ДНК?', '请问，DNA代表什么？'),
    ('Generate, if you please, a list of random words.', 'Сгенерируй, пожалуйста, список случайных слов.', '请生成一个随机单词列表。'),
    ("Who, in your opinion, is the world's most famous painter?", 'Кто, по вашему мнению, самый известный художник в мире?', '依您看，世界上最著名的画家是谁？'),
    ('Look up, if you would, the boiling point of water.', 'Укажи, пожалуйста, температуру кипения воды.', '请查找水的沸点。'),
    ('Explain, if possible, the concept of artificial intelligence in simple terms.', 'Объясни, если возможно, концепцию искусственного интеллекта простыми словами.', '如果可以的话，用简单的术语解释人工智能的概念。'),
    ('Generate, if you please, a poem with 10 lines.', 'Напиши, пожалуйста, стихотворение из 10 строк.', '请创作一首10行的诗。'),
    ('Calculate, if possible, the total surface area of a cube with a side length of 5 cm.', 'Рассчитай, если возможно, общую площадь поверхности куба с длиной стороны 5 см.', '如果可以的话，计算边长为5厘米的立方体的总表面积。'),
    ('What, in your opinion, is the force on a 1 kg mass due to the gravitational force?', 'Чему, по вашему мнению, равна сила гравитации, действующая на тело массой 1 кг?', '依您看，1千克质量的物体所受的重力是多少？'),
    ('Give, if you would, two examples of a liquid.', 'Назови, пожалуйста, два примера жидкости.', '请给出液体的两个例子。'),
    ("What, if you don't mind, is the product of 6 and 2?", 'Чему, если не сложно, равно произведение 6 и 2?', '请问，6乘以2等于多少？'),
    ('Construct, if you would, a list of tips to help reduce stress.', 'Составь, пожалуйста, список советов для снижения стресса.', '请列出帮助减轻压力的建议。'),
    ('Compare, if you would, cats and dogs.', 'Сравни, пожалуйста, кошек и собак.', '请比较猫和狗。'),
    ('Write, if you would, a short review for the novel "Master and Margarita".', 'Напиши, пожалуйста, краткую рецензию на роман "Мастер и Маргарита".', '请为小说《大师与玛格丽特》写一篇简短的书评。')
    ]

prompts_passiv = [
    ('Let three tips for staying healthy be given.', 'Три совета для поддержания здоровья должны быть названы.', '保持健康的三个建议应该被给出。'),
    ('What are the three primary colors considered to be?', 'Какие три основных цвета считаются существующими?', '三原色被认为是哪些？'),
    ('How can air pollution be reduced?', 'Как может быть снижено загрязнение воздуха?', '空气污染如何被减少？'),
    ('How was Julius Caesar killed?', 'Как был убит Юлий Цезарь?', '尤利乌斯·凯撒是怎么被杀的？'),
    ('What is considered to be the capital of France?', 'Что считается столицей Франции?', '法国的首都被认为是哪里？'),
    ('Let a list of ten items a person might need for a camping trip be generated.', 'Список из десяти вещей, которые могут понадобиться в походе, должен быть составлен.', '一个人露营时可能需要的十件物品应该被列出。'),
    ('Let three verbs that mean the same as "to apologize" be generated.', 'Три глагола, синонимичных слову "извиняться", должны быть названы.', '三个与“道歉”意思相同的动词应该被生成。'),
    ('What is meant by DNA?', 'Что подразумевается под аббревиатурой ДНК?', 'DNA被代表什么？'),
    ('Let a list of random words be generated.', 'Список случайных слов должен быть сгенерирован.', '一个随机单词列表应该被生成。'),
    ('Who is considered to be the world\'s most famous painter?', 'Кем считается самый известный художник в мире?', '世界上最著名的画家被认为是誰？'),
    ('Let the boiling point of water be looked up.', 'Температура кипения воды должна быть указана.', '水的沸点应该被查找。'),
    ('Let the concept of artificial intelligence be explained in simple terms.', 'Концепция искусственного интеллекта должна быть объяснена простыми словами.', '人工智能的概念应该用简单的术语被解释。'),
    ('Let a poem with 10 lines be generated.', 'Стихотворение из 10 строк должно быть написано.', '一首10行的诗应该被创作。'),
    ('Let the total surface area of a cube with a side length of 5 cm be calculated.', 'Общая площадь поверхности куба с длиной стороны 5 см должна быть рассчитана.', '边长为5厘米的立方体的总表面积应该被计算。'),
    ('What force is exerted on a 1 kg mass by the gravitational force?', 'Какова сила, оказываемая гравитацией на тело массой 1 кг?', '1千克质量的物体被重力所施加的力是多少？'),
    ('Let two examples of a liquid be given.', 'Два примера жидкости должны быть названы.', '液体的两个例子应该被给出。'),
    ('What result is obtained when 6 is multiplied by 2?', 'Каков результат, когда 6 умножается на 2?', '6乘以2的结果是多少？'),
    ('Let a list of tips to help reduce stress be constructed.', 'Список советов для снижения стресса должен быть составлен.', '帮助减轻压力的建议应该被列出。'),
    ('Let cats and dogs be compared.', 'Кошки и собаки должны быть сравнены.', '猫和狗应该被比较。'),
    ('Let a short review for the novel "Master and Margarita" be written.', 'Краткая рецензия на роман "Мастер и Маргарита" должна быть написана.', '小说《大师与玛格丽特》的一篇简短的书评应该被写。')
    ]

prompts_anafora = [
    ('Give three tips for staying healthy. Give three tips that will help maintain good health.',
     'Назови три совета для поддержания здоровья. Назови три совета, которые помогут сохранить здоровье.',
     '给出保持健康的三个建议。给出三个能够帮助保持健康的建议。'),
    ('What are the three primary colors? What are the three colors that are considered primary?',
     'Какие три основных цвета существуют? Какие три цвета считаются основными?',
     '三原色是什么？三种被认为是原色的颜色是什么？'),
    ('How can we reduce air pollution? How can we take steps to minimize air pollution?',
     'Как можно снизить загрязнение воздуха? Как можно предпринять шаги для уменьшения загрязнения воздуха?',
     '我们如何减少空气污染？我们如何采取措施减少空气污染？'),
    ('How did Julius Caesar die? How did the famous Julius Caesar meet his end?',
     'Как умер Юлий Цезарь? Как скончался знаменитый Юлий Цезарь?',
     '尤利乌斯·凯撒是怎么死的？尤利乌斯·凯撒是如何结束生命的？'),
    ('What is the capital of France? What city serves as the capital of France?',
     'Какова столица Франции? Какой город является столицей Франции?',
     '法国的首都是哪里？哪个城市是法国的首都？'),
    ('Generate a list of ten items a person might need for a camping trip. Generate a list of ten essential items for a camping trip.',
     'Составь список из десяти вещей, которые могут понадобиться в походе. Составь список десяти необходимых вещей для похода.',
     '列出一个人露营时可能需要的十件物品。列出十件露营时必需的物品。'),
    ('Generate three verbs that mean the same as "to apologize". Generate three verbs synonymous with "to apologize".',
     'Назови три глагола, синонимичных слову "извиняться". Назови три глагола, имеющих значение "извиняться".',
     '生成三个与“道歉”意思相同的动词。生成三个意思相近的“道歉”动词。'),
    ('What does DNA stand for? What is the full form of DNA?',
     'Что означает аббревиатура ДНК? Как расшифровывается аббревиатура ДНК?',
     'DNA代表什么？DNA的全称是什么？'),
    ('Generate a list of random words. Generate a collection of random words.',
     'Сгенерируй список случайных слов. Сгенерируй подборку случайных слов.',
     '生成一个随机单词列表。生成一个随机单词的集合。'),
    ("Who is the world's most famous painter? Who is the painter most widely recognized in the world?",
     'Кто самый известный художник в мире? Кто является самым узнаваемым художником в мире?',
     '世界上最著名的画家是谁？世界上最广为人知的画家是谁？'),
    ('Look up the boiling point of water. Look up the temperature at which water boils.',
     'Укажи температуру кипения воды. Укажи, при какой температуре закипает вода.',
     '查找水的沸点。查找水达到沸腾的温度。'),
    ('Explain the concept of artificial intelligence in simple terms. Explain artificial intelligence in a way that is easy to understand.',
     'Объясни концепцию искусственного интеллекта простыми словами. Объясни искусственный интеллект так, чтобы было понятно.',
     '用简单的术语解释人工智能的概念。用易于理解的方式解释人工智能。'),
    ('Generate a poem with 10 lines. Generate a poem consisting of exactly 10 lines.',
     'Напиши стихотворение из 10 строк. Напиши стихотворение, состоящее ровно из 10 строк.',
     '创作一首10行的诗。创作一首由10行组成的诗歌。'),
    ('Calculate the total surface area of a cube with a side length of 5 cm. Calculate the total area of all six faces of a cube with a 5 cm side.',
     'Рассчитай общую площадь поверхности куба с длиной стороны 5 см. Рассчитай площадь всех шести граней куба со стороной 5 см.',
     '计算边长为5厘米的立方体的总表面积。计算边长为5厘米的立方体所有六个面的总面积。'),
    ('What is the force on a 1 kg mass due to the gravitational force? What is the weight of a 1 kg mass due to gravity?',
     'Чему равна сила гравитации, действующая на тело массой 1 кг? Каков вес тела массой 1 кг под действием гравитации?',
     '1千克质量的物体所受的重力是多少？1千克质量的物体在重力作用下的重量是多少？'),
    ('Give two examples of a liquid. Give two substances that exist in a liquid state.',
     'Назови два примера жидкости. Назови два вещества, находящихся в жидком состоянии.',
     '给出液体的两个例子。给出两种处于液态的物质。'),
    ('What is the product of 6 and 2? What do you get when you multiply 6 by 2?',
     'Чему равно произведение 6 и 2? Какой результат получится, если умножить 6 на 2?',
     '6乘以2等于多少？6和2相乘的结果是多少？'),
    ('Construct a list of tips to help reduce stress. Construct a set of helpful suggestions for managing stress.',
     'Составь список советов для снижения стресса. Составь перечень полезных рекомендаций по снижению стресса.',
     '列出帮助减轻压力的建议。列出一组有助于减轻压力的建议。'),
    ('Compare cats and dogs. Compare these two popular pets: cats and dogs.',
     'Сравни кошек и собак. Сравни этих двух популярных домашних животных: кошек и собак.',
     '比较猫和狗。比较这两种常见的宠物：猫和狗。'),
    ('Write a short review for the novel "Master and Margarita". Write a brief critique of "Master and Margarita".',
     'Напиши краткую рецензию на роман "Мастер и Маргарита". Напиши краткий анализ романа "Мастер и Маргарита".',
     '为小说《大师与玛格丽特》写一篇简短的书评。为《大师与玛格丽特》写一篇简要的评论。')]

prompts_ellipsis = [
    ('Three tips for staying healthy?', 'Три совета для здоровья?', '保持健康的三个建议？'),
    ('Three primary colors?', 'Три основных цвета?', '三原色？'),
    ('Reduce air pollution?', 'Снизить загрязнение воздуха?', '减少空气污染？'),
    ('Julius Caesar\'s death?', 'Смерть Юлия Цезаря?', '尤利乌斯·凯撒之死？'),
    ('Capital of France?', 'Столица Франции?', '法国首都？'),
    ('Ten camping trip items?', 'Десять вещей для похода?', '露营十件物品？'),
    ('Three verbs for "to apologize"?', 'Три глагола вместо "извиняться"?', '“道歉”的三个动词？'),
    ('DNA abbreviation?', 'Аббревиатура ДНК?', 'DNA缩写？'),
    ('Random words list?', 'Список случайных слов?', '随机单词列表？'),
    ('World\'s most famous painter?', 'Самый известный художник?', '最著名画家？'),
    ('Water\'s boiling point?', 'Температура кипения воды?', '水的沸点？'),
    ('Artificial intelligence explained simply?', 'ИИ простыми словами?', '简单解释人工智能？'),
    ('10-line poem?', 'Стихотворение из 10 строк?', '十行诗？'),
    ('Surface area of 5cm cube?', 'Площадь куба 5 см?', '5厘米立方体表面积？'),
    ('Gravitational force on 1kg?', 'Гравитация на 1 кг?', '1千克物体的重力？'),
    ('Two liquid examples?', 'Два примера жидкости?', '液体的两个例子？'),
    ('6 multiplied by 2?', '6 умножить на 2?', '6乘2？'),
    ('Stress reduction tips?', 'Советы против стресса?', '减压建议？'),
    ('Cats vs dogs?', 'Кошки и собаки?', '猫和狗？'),
    ('"Master and Margarita" review?', 'Рецензия на "Мастера и Маргариту"?', '《大师与玛格丽特》书评？')
]

prompts_inversia = [
    ('Three tips for staying healthy, give.', 'Три совета для поддержания здоровья назови.' ,'保持健康的三个建议，给出。'),
    ('The three primary colors are what?', 'Существуют ли три основных цвета, какие?' ,  '是什么，三原色？'),
    ('Air pollution, how can we reduce?', 'Загрязнение воздуха снизить, как можно?', '空气污染，我们如何减少？'),
    ('Julius Caesar, how did he die?', 'Юлий Цезарь как умер?', '是怎么死的，尤利乌斯·凯撒？'),
    ('The capital of France is what?', 'Столица Франции какова?' ,  '是哪里，法国的首都？'),
    ('A list of ten items a person might need for a camping trip, generate.',
     'Список из десяти вещей, которые могут понадобиться в походе, составь.',
     '一个人露营时可能需要的十件物品，列出。'),
    ('Three verbs that mean the same as "to apologize", generate.',
     'Три глагола, синонимичных слову "извиняться", назови.',
     '三个与“道歉”意思相同的动词，生成。'),
    ('DNA stands for what?', 'Аббревиатура ДНК что означает?', '什么，DNA代表？'),
    ('A list of random words, generate.', 'Список случайных слов сгенерируй.', '一个随机单词列表，生成。'),
    ("The world's most famous painter is who?", 'Самый известный художник в мире кто?', '是谁，世界上最著名的画家？'),
    ('The boiling point of water, look up.', 'Температуру кипения воды укажи.', '水的沸点，查找。'),
    ('The concept of artificial intelligence in simple terms, explain.',
     'Концепцию искусственного интеллекта простыми словами объясни.',
     '人工智能的概念，用简单的术语解释。'),
    ('A poem with 10 lines, generate.', 'Стихотворение из 10 строк напиши.', '一首10行的诗，创作。'),
    ('The total surface area of a cube with a side length of 5 cm, calculate.',
     'Общую площадь поверхности куба с длиной стороны 5 см рассчитай.',
     '边长为5厘米的立方体的总表面积，计算。'),
    ('The force on a 1 kg mass due to the gravitational force is what?',
     'Сила гравитации, действующая на тело массой 1 кг, чему равна?',
     '是多少，1千克质量的物体所受的重力？'),
    ('Two examples of a liquid, give.', 'Два примера жидкости назови.', '液体的两个例子，给出。'),
    ('The product of 6 and 2 is what?', 'Произведение 6 и 2 чему равно?', '等于多少，6乘以2？'),
    ('A list of tips to help reduce stress, construct.', 'Список советов для снижения стресса составь.', '帮助减轻压力的建议，列出。'),
    ('Cats and dogs, compare.', 'Кошек и собак сравни.', '猫和狗，比较。'),
    ('A short review for the novel "Master and Margarita", write.',
     'Краткую рецензию на роман "Мастер и Маргарита" напиши.',
     '一篇简短的书评，为小说《大师与玛格丽特》写。')
]

#for making prompts.json
for i in zip(prompts, prompts_passiv, prompts_add, prompts_anafora, prompts_ellipsis, prompts_inversia):
    print(f'"en": ( "default": "{i[0][0]}", "passive": "{i[1][0]}", "inserted": "{i[2][0]}", "anaphora": "{i[3][0]}","ellipsis": "{i[4][0]}","inversion": "{i[5][0]}"),')
    print(f'"ru": ( "default": "{i[0][1]}", "passive": "{i[1][1]}", "inserted": "{i[2][1]}", "anaphora": "{i[3][1]}","ellipsis": "{i[4][1]}","inversion": "{i[5][1]}"),')
    print(f'"ch": ( "default": "{i[0][2]}", "passive": "{i[1][2]}", "inserted": "{i[2][2]}", "anaphora": "{i[3][2]}","ellipsis": "{i[4][2]}","inversion": "{i[5][2]}"),')
    # print(i[0][0], i[1][0], i[2][0], i[3][0], i[4][0], i[5][0])